Separate opcodes page for each TEAL version
algorand/docs pull request #1156
Opened 2023-08-08 00:24 UTC by jasonpaulos

Companion PR to https://github.com/algorand/go-algorand/pull/5629, which generates a `TEAL_opcodes_v%d.md` file for each TEAL version, instead of just a single `TEAL_opcodes.md` file.

This change allows the docs site to show all available opcodes markdown files.

The real change is in `scripts/reformat-all-commands.sh`, which changes how the files are copied in from go-algorand.

2023-09-27 19:17 UTC, ryanRfox requested changes
Please modify the links to **jsonspec.md** in the following files:
- v9.md
- v8.md
- v7.md

Check this section of code for the invalid link (in needs to be one level prior):
```
## json_ref

- Syntax: `json_ref R` ∋ R: [json_ref](#field-group-json_ref)
- Bytecode: 0x5f {uint8}
- Stack: ..., A: []byte, B: []byte &rarr; ..., any
- key B's value, of type R, from a [valid](jsonspec.md) utf-8 encoded json object A
- **Cost**: 25 + 2 per 7 bytes of A
- Availability: v7
```

I'll suggest:
```
- key B's value, of type R, from a valid utf-8 encoded json object A (see: [JSON Spec](../jsonspec.md))
```

2023-09-28 15:46 UTC, jasonpaulos commented
Good catch @ryanRfox. I've updated the script to fix that link, and I have regenerated the files based on the latest go-algorand changes

2023-10-04 11:34 UTC, nullun reviewed
Thanks for doing this! I made a small PR to your fork that updates the links to the latest opcode version, but otherwise I'm happy with it. https://github.com/jasonpaulos/algorand-docs/pull/1/files

2023-10-04 17:36 UTC, ryanRfox approved these changes

2023-10-05 18:38 UTC, merged