Raf indexer accounts application
algorand/docs pull request #231
Opened 2020-09-10 21:56 UTC by rfustino

Samples and doc updated for accounts search for application. Paging example as well.

2020-11-06 19:28 UTC, ryanRfox requested changes
[ ] Set port to 8980 throughout
[ ] Remove references to Pure Stake API throughout
[ ] Remove references to AWS DB throughout
[ ] Remove extraneous commented lines with testing parameters

2020-11-06 19:28 UTC, ryanRfox commented on examples/indexer/java/AccountsAppID.java
> +        // TODO  remove
Remove

2020-11-06 19:28 UTC, ryanRfox commented on examples/indexer/java/AccountsAppID.java
> +        final int INDEXER_API_PORT = 59998;
Should be 8980 throughout 

Reference default setting:
https://github.com/algorand/indexer/blob/7e7f1c34d6f930a424a6030750fe1d7a54006d2d/cmd/algorand-indexer/daemon.go#L115

2020-11-06 19:28 UTC, ryanRfox commented on examples/indexer/javascript/accountsApplicationID.js
> +// const indexer_server = "https://testnet-algorand.api.purestake.io/idx2/";
Remove

2021-01-24 16:37 UTC, ejbaran commented
PR is out of date. Closing.

2021-01-24 16:37 UTC, closed without merging