Feature/start building explore
algorand/docs pull request #399
Opened 2021-05-25 15:15 UTC by edwardgaudio

**Is your addition related to a problem? Please describe.**
Make start building and explore sections style consistent with work done previously for stateless contracts, up to par with modern js. Also I ran across some oddities I just ended up removing or adjusting.

**Describe the solution you'd like**
Same as before, combination of main async function with then/catch promise syntax.

**Additional context**
WIP at the moment unless we wanna break this up into multiple pr's

2021-05-26 18:26 UTC, ryanRfox requested changes
Good stuff here. Just a few minor changes.

2021-05-26 18:26 UTC, ryanRfox commented on docs/features/transactions/signatures.md
> +    // ...covered in a previous example
I feel this method must be included within this script as the reader may not access related content and we want the code to be complete inline.

2021-05-26 18:26 UTC, ryanRfox commented on examples/accounts/v2/javascript/package.json
> +{
These package.json files should be removed, as the license is covered here:
https://github.com/algorand/docs/blob/staging/LICENSE.md

2021-05-26 18:26 UTC, ryanRfox commented on examples/multisig/v2/javascript/package.json
> +{
remove

2021-05-26 18:26 UTC, ryanRfox commented on examples/smart_contracts/v1/javascript/AccountDelegation.js
> +    const receiver = "HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA";
Please us v2 dispenser HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA

2021-05-26 18:26 UTC, ryanRfox commented on examples/smart_contracts/v1/javascript/ContractAccount.js
> +    const receiver = "GVVIH6IE3ZAFLIQF6UFBOH4TI5ZOPHFRMDQUTXQRKZ6XWSRTVRDBQ4GZLY";
HZ57J3K46JIJXILONBBZOHX6BKPXEM2VVXNRFSUED6DKFD5ZD24PMJ3MVA

2021-05-26 18:26 UTC, ryanRfox commented on examples/smart_contracts/v1/javascript/package.json
> +{
remove

2021-05-26 18:26 UTC, ryanRfox commented on examples/smart_contracts/v1/javascript/utils/waitForConfirmation.js
> +// Function used to wait for a tx confirmation
I like this :)

2021-05-26 18:26 UTC, ryanRfox commented on examples/smart_contracts/v2/javascript/package.json
> +{
remove

2021-06-11 20:41 UTC, ryanRfox commented
ping @edwardgaudio just a couple edit to get us over the line :)

2021-07-01 19:56 UTC, ryanRfox approved these changes
LGTM

2021-07-02 02:29 UTC, edwardgaudio commented
> LGTM

Conflicts resolved and ready to go @ryanRfox

2021-10-26 10:33 UTC, closed without merging