Raf js gettingstarted
algorand/docs pull request #462
Opened 2021-07-02 14:32 UTC by rfustino

2021-09-13 20:28 UTC, ejbaran approved these changes

2021-09-13 20:33 UTC, ejbaran requested changes
I approved too early. This is in the wrong location. Should be docs/sdks/javascript/index.md

2021-09-14 22:48 UTC, rfustino commented
moved to docs/sdks/javascript/index.md

2021-09-15 02:24 UTC, ejbaran approved these changes

2021-09-15 02:24 UTC, merged