Update guidelines.md
algorand/docs pull request #623
Opened 2021-10-30 08:52 UTC by kr5hn4

2021-10-30 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/docs?pullRequest=623) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/docs?pullRequest=623) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/docs?pullRequest=623) it.</sub>

2021-10-30 10:09 UTC, barnjamin commented
Thanks! Can you please sign the CLA?

2021-12-02 13:25 UTC, barnjamin requested changes
Good change, thanks! Please sign the CLA so we can merge.

2022-01-07 16:58 UTC, barnjamin approved these changes

2022-01-14 20:18 UTC, ryanRfox approved these changes
lgtm

2022-01-14 20:18 UTC, merged