Remove "this is ignored" message in BaseLoggerDebugLevel
algorand/docs pull request #666
Opened 2021-12-26 20:15 UTC by Latonis

Fixed BaseLoggerDebugLevel entry to reflect current status of the default value being 4 and it able to be changed.

2021-12-26 20:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/docs?pullRequest=666) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/docs?pullRequest=666) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/docs?pullRequest=666) it.</sub>

2021-12-27 13:24 UTC, barnjamin requested changes
Thanks! 

Can you target staging please?

2021-12-27 15:19 UTC, Latonis commented
Sorry about that, fixed now!

2021-12-27 15:35 UTC, barnjamin approved these changes
LGTM, Thanks!

2022-01-07 15:09 UTC, merged