Add files via upload
algorand/docs pull request #997
Opened 2023-01-25 22:39 UTC by algodev2

The 9 files to separate the installation files uploaded for review. Notes:
1. All files need to be reviewed for format, and links updated to .md format
2. Debian and RedHat files are same except for beginning install process.
3. OtherLinux and Mac could be the same, but left Mac separate.
4. The changes should be updated in existing Algorand switch-networks file for making a new service. It shows only instance-template-unit file way.
5. Still need to explain editing template-unit file vs. instance-template-unit file. But didn't do as ConfigureAlgodService as feel it needs much more explaination on systemd file editing. Please decide for me.

2023-01-25 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/docs?pullRequest=997) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/docs?pullRequest=997) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/docs?pullRequest=997) it.</sub>

2023-01-26 04:35 UTC, algodev2 commented
Forgot to remove <pre> and </pre> tags from files. I removed and re-uploading.
Also forgot to include GivePermissionRunAsAlgorandUser.md file

2023-01-31 20:47 UTC, onetechnical requested changes
I only did a quick pass through here, but can you check all the link anchors? There are a lot of broken links in here.

2023-01-31 20:47 UTC, onetechnical commented on docs/run-a-node/setup/InstallANode.md
> +
These URLs above don't seem right.

2023-01-31 20:47 UTC, onetechnical commented on docs/run-a-node/setup/InstallANode.md
> +
Same with these - I think they're not linking to the right place/formatted correctly.

2023-01-31 20:47 UTC, onetechnical commented on docs/run-a-node/setup/GivePermissionsRunAsAlgorandUser.md
> +After installing with package manager for Debian or Red Hat distributions and want to customize a different user to be run algorand goal commands requires elevated permissions.
```suggestion
After installing with package manager for Debian or Red Hat distributions you may want to customize a different user to be able to run algorand goal commands, which requires elevated permissions for that user.

```

2023-01-31 20:47 UTC, onetechnical commented on docs/run-a-node/setup/GivePermissionsRunAsAlgorandUser.md
> +Then vi a new file named algodevuser
```suggestion
Then edit a new file named algodevuser

```

2023-01-31 20:47 UTC, onetechnical commented on docs/run-a-node/setup/GivePermissionsRunAsAlgorandUser.md
> +The name `algodevuser` is arbitrary, but to give relevancy to you later. Change as necessary.
```suggestion
The name `algodevuser` is arbitrary. Change as appropriate to your user.

```

2023-01-31 20:47 UTC, onetechnical commented on docs/run-a-node/setup/InstallANodeConfigureAlgodService.md
> +- username, user run command that will run algorand.service
```suggestion
- username, user that will run algorand.service

```

2023-10-26 14:27 UTC, ryanRfox commented
closing for lack of progress

2023-10-26 14:27 UTC, closed without merging